### ISSUE TITLE
Does almalinux and rocky linux being correctly detected ?

### ISSUE THREAD

**Issue by buzzzo** [furlongm/patchman#344] opened 2021-09-11 15:31 UTC
When try to report an almalinux host (aka rhel8.x clone) patchman detect updates even if the system is up to date.
Patchman detect a package from addon repo (remi and so on) as updates for base package even if a classic "yum update" does not detect this.

**Comment by vroca** [comment] 2021-09-16 07:22
I have the same problem in AlmaLinux, Rocky and CentOS 8.4. Patchman notifies updates for packages that come from the Modules of the AppStream repository. However, these modules are disabled and "dnf check-update" does not show this. Interestingly the name of the updates contain the string "module".
![screenshot](https://user-images.githubusercontent.com/49186720/133567243-f26e5454-cc1e-462d-8f67-047c3643876a.png)

**Comment by furlongm** [comment] 2021-09-16 13:41
Could you see if this commit from the `modularity` branch works? a47329445ae089c709896b23f072b047cfbffe16

**Comment by vroca** [comment] 2021-09-21 12:19
This branch doesn't work. It fails when I try running the command `patchman -p`: 
```
Processing Reports for all Hosts
Reverse DNS check disabled 
patchman.localhost repos              100%|##################|Time: 0:00:00
Traceback (most recent call last):      0%|                  |ETA:  --:--:--
   File "./sbin/patchman", line 687, in <module>
     main()
   File "./sbin/patchman", line 681, in main
     showhelp = process_args(args)
   File "./sbin/patchman", line 641, in process_args
     process_reports(args.host, args.force)
   File "./sbin/patchman", line 473, in process_reports
     report.process(find_updates=False)
   File "/usr/lib/python2.7/site-packages/patchman-1.2.24-py2.7.egg/reports/models.py", line 161, in process
     process_packages(report=self, host=host)
   File "/usr/lib/python2.7/site-packages/patchman-1.2.24-py2.7.egg/reports/utils.py", line 80, in process_packages
     package = process_package(pkg_str, report.protocol)
   File "/usr/lib/python2.7/site-packages/patchman-1.2.24-py2.7.egg/reports/utils.py", line 314, in process_package
     if pkg[5] == 'deb':
 IndexError: list index out of range
```

**Comment by furlongm** [comment] 2021-10-04 01:58
Could you confirm that this is still an issue with v2?

**Comment by cshabazian** [comment] 2021-11-25 18:41
I can confirm this is still an issue with 2.01-1.  The issue is only with the modules stream (at least on my systems).  

As an fyi, updating to the latest module stream can cause issues (example, perl) unless all of the dependent packages have been modularized.  Additionally, the default version of modules are the version that is API stable and supported/updated for 10 years whereas the later modules will usually be just for the lifecycle of the module.  Switching to a later module is not recommended unless it's necessary and you understand what it involves.

**Comment by furlongm** [comment] 2023-12-07 15:41
This should be fixed in version 3. Please let me know if you have any further issues.

**Closed by furlongm** 2023-12-07 15:41 UTC
