### ISSUE TITLE
High CPU usage, Dashboard inaccessible

### ISSUE THREAD

**Issue by zubfatal** [furlongm/patchman#28] opened 2017-03-09 13:38 UTC
I'm using Ubuntu 16.04.2 (64bit), MariaDB 10.0.29 and followed the git install instructions.
Installation itself was successful , but when running `manage.py` it threw an error about `pymysql` not installed.

```
Traceback (most recent call last):
  File "./manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 41, in <module>
    class Permission(models.Model):
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 139, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/lib/python2.7/dist-packages/django/db/models/options.py", line 250, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/lib/python2.7/dist-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 241, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 112, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 23, in <module>
    import pymysql
ImportError: No module named pymysql
```
Easily fixed by doing `apt-get install python-pymysql`

With no data at all, dashboard loads fine, but I noticed while `patchman -a` was running (local data) i got 100% CPU usage. I started with a Digital Ocean droplet with 1GB RAM and 1xCPU, later I tried upgrading it to 2GB RAM and 2xCPUs, also 100% usage on both recently i've upgraded it to 8GB RAM and 4xCPUs, still getting 100% CPU usage on some of the CPUs, but even worse, once the database has actual content, loading the dashboard seems impossible.

I have done no optimization for MySQL, and it seems to be a query issue specifically:
```
SELECT COUNT(*) FROM (SELECT DISTINCT `packages_package`.`id` AS Col1, `packages_package`.`name_id` AS Col2, `packages_package`.`epoch` AS Col3, `packages_package`.`version` AS Col4, `packages_package`.`release` AS Col5, `packages_package`.`arch_id` AS Col6, `packages_package`.`packagetype` AS Col7, `packages_package`.`description` AS Col8, `packages_package`.`url` AS Col9 FROM `packages_package` LEFT OUTER JOIN `hosts_host_packages` ON ( `packages_package`.`id` = `hosts_host_packages`.`package_id` ) LEFT OUTER JOIN `repos_mirrorpackage` ON ( `packages_package`.`id` = `repos_mirrorpackage`.`package_id` ) WHERE (`hosts_host_packages`.`host_id` IS NULL AND `repos_mirrorpackage`.`mirror_id` IS NULL)) subquery;
```
it just goes on forever and ever and causing 100% CPU usage on atleast 1 CPU.

As the latest test, I removed `python-pymysql` - then the dashboard loads instantly, but then `manage.py` and the actual `patchman -a` doesn't work.

**Comment by furlongm** [comment] 2017-03-09 13:42
Install python-mysql or similar?

**Comment by zubfatal** [comment] 2017-03-09 13:48
Sorry, initially i accidently pressed enter beforing finishing.

**Comment by furlongm** [comment] 2017-03-14 23:27
Can you try installing python-mysqldb instead of python-pymysql?

**Comment by zubfatal** [comment] 2017-03-16 10:45
Both `python-mysqldb` and `python-pymysql` are installed, it seems neither dashboard or CLI scripts works without `python-pymysql`.

**Comment by furlongm** [comment] 2017-03-16 10:46
Is DEBUG=True enabled in settings.py anywhere?

**Comment by zubfatal** [comment] 2017-03-16 10:48
I haven't changed anything in settings.py but I do have a /etc/patchman/local_settings.py file, it uses `DEBUG = False`

**Comment by zubfatal** [comment] 2017-03-16 10:54
I can't remember the exact error messages, but the first time i ran `./manage.py syncdb` I got an error about restraints or indexes, but no errors when running it a second time. I can clear the database and start from scratch if needed.

**Comment by furlongm** [comment] 2017-03-16 11:19
Maybe starting from scratch would help. I cannot reproduce the issue, when following INSTALL on Ubuntu.

**Comment by zubfatal** [comment] 2017-03-16 13:20
I can't remember the exact error messages, but the first time i ran `./manage.py syncdb` I got an error about restraints or indexes, but no errors when running it a second time. I can clear the database and start from scratch if needed.

**Comment by zubfatal** [comment] 2017-03-16 13:31
I removed the database, and re-created it.
Running `./manage.py syncdb` for the first time threw this error:
```
    Running deferred SQL...
Traceback (most recent call last):
  File "./manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 318, in sync_apps
    cursor.execute(statement)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 127, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 966, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
django.db.utils.InternalError: (1005, u'Can\'t create table `patchman`.`#sql-1fb5_8cfe` (errno: 150 "Foreign key constraint is incorrectly formed")')
```
Running it a second time did not give any errors, and i proceeded with: `./manage.py migrate` and `./manage.py collectstatic` without any problems.

Finally I ran the client `patchman-client -s http://127.0.0.1/patchman` and `patchman -a`
After this, I'm back to the same issue, trying to login in the dashboard is taking forever (waiting for the query to complete)

**Comment by zubfatal** [comment] 2017-03-16 14:01
I removed the database, and re-created it.
Running `./manage.py syncdb` for the first time threw this error:
```
    Running deferred SQL...
Traceback (most recent call last):
  File "./manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 318, in sync_apps
    cursor.execute(statement)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 127, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 966, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
django.db.utils.InternalError: (1005, u'Can\'t create table `patchman`.`#sql-1fb5_8cfe` (errno: 150 "Foreign key constraint is incorrectly formed")')
```
Running it a second time did not give any errors, and i proceeded with: `./manage.py migrate` and `./manage.py collectstatic` without any problems.

Finally I ran the client `patchman-client -s http://127.0.0.1/patchman` and `patchman -a`
After this, I'm back to the same issue, trying to login in the dashboard is taking forever (waiting for the query to complete)

**Comment by zubfatal** [comment] 2017-03-16 14:03
I've also tried creating an Ubuntu 14.04 server and followed the instructions for the 14.04 installation, which throws this error after running `patchman-manage syncdb`:
```
Creating tables ...
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table auth_user_groups
Creating table auth_user_user_permissions
Creating table auth_user
Creating table django_content_type
Creating table django_session
Creating table django_site
Creating table django_admin_log
Creating table tagging_tag
Creating table tagging_taggeditem
Creating table hosts_host_updates
Creating table hosts_host_packages
Creating table hosts_host
Creating table hosts_hostrepo
Creating table domains_domain
Creating table operatingsystems_osgroup_repos
Creating table operatingsystems_osgroup
Creating table operatingsystems_os
Creating table packages_packagename
Creating table packages_package
Traceback (most recent call last):
  File "/usr/bin/patchman-manage", line 7, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 107, in handle_noargs
    cursor.execute(statement)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 51, in execute
    return self.cursor.execute(sql)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 1000 bytes')
```
Also that guide refers to editting /etc/patchman/local_settings.py but the actual file is /etc/patchman/settings.py

**Comment by furlongm** [comment] 2017-03-23 14:00
The deb instructions are probably out of date by now. I'm going to have to rewrite the installation instuctions for jessie and xenial. If you make any progress in the meantime, let me know.

**Comment by furlongm** [comment] 2017-03-27 11:22
Can you try the debs that are located here -> https://www.openbytes.ie/tmp/

**Comment by zubfatal** [comment] 2017-03-27 13:22
On the 14.04 or 16.04 server?

**Comment by furlongm** [comment] 2017-03-27 14:12
16.04

**Comment by zubfatal** [comment] 2017-03-27 14:59
So far, I've run into more or less the same problem as with the 14.04 install from repository:
```
root@patchman:~$ patchman-manage syncdb
Operations to perform:
  Synchronize unmigrated apps: staticfiles, admindocs, repos, messages, reports, util, domains, humanize, hosts, operatingsystems, django_extensions, rest_framework, packages, arch, bootstrap3
  Apply all migrations: sessions, admin, sites, auth, contenttypes, tagging
Synchronizing apps without migrations:
  Creating tables...
    Creating table hosts_host
    Creating table hosts_hostrepo
    Creating table domains_domain
    Creating table operatingsystems_osgroup
    Creating table operatingsystems_os
    Creating table packages_packagename
    Creating table packages_package
Traceback (most recent call last):
  File "/usr/bin/patchman-manage", line 7, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 310, in sync_apps
    editor.create_model(model)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 127, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 966, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
django.db.utils.InternalError: (1071, u'Specified key was too long; max key length is 1000 bytes')
```

**Comment by furlongm** [comment] 2017-03-28 00:04
Ok, that's odd I can't reproduce that. What mysql server are you using?

**Comment by zubfatal** [comment] 2017-03-28 13:47
I'm using mysql-server 5.7.17
Looking at the dependencies of the `python-patchman_1.0.5-1_all.deb` file, I've installed the following packages:
```
apache2 2.4.18-2ubuntu3.1 amd64
dbconfig-mysql 2.0.4ubuntu1 all
libapache2-mod-wsgi 4.3.0-1.1build1 amd64
mysql-server 5.7.17-0ubuntu0.16.04.1 all
python 2.7.11-1 amd64
python-colorama 0.3.7-1 all
python-debian 0.1.27ubuntu2 all
python-django 1.8.7-1ubuntu5.4 all
python-django-extensions 1.5.9-1 all
python-django-tagging 1:0.4-1 all
python-djangorestframework 3.3.2-2 all
python-humanize 0.5.1-2 all
python-lxml 3.5.0-1build1 amd64
python-pip 8.1.1-2ubuntu0.4 all
python-progressbar 2.3-2 all
python-pymysql 0.7.2-1ubuntu1 all
python-requests 2.9.1-3 all
python-rpm 4.12.0.1+dfsg1-3build3 amd64
```
Some of the tables has been created when running `patchman-manage syncdb`:
```
django_migrations
domains_domain
hosts_host
hosts_host_packages
hosts_host_updates
hosts_hostrepo
operatingsystems_os
operatingsystems_osgroup
operatingsystems_osgroup_repos
packages_packagename
```
It seems to stop at
```
Synchronizing apps without migrations:
  Creating tables...
    Creating table packages_package
...
```
Before dumping the error previously mentioned.

It seems like it's an issue with the index it's trying to use when creating the table (haven't found where it actually does that)
http://stackoverflow.com/a/20014300
http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/

It seems like the server is already using the `innodb_large_prefix` variable.
`innodb_file_format` is also set to `Barracuda`.

**Comment by furlongm** [comment] 2017-11-30 04:53
Apologies, this dropped off my radar. I'm updating the instructions now but can't reproduce this issue. Are you still experiencing it?

**Comment by zubfatal** [comment] 2017-12-05 13:13
I must admit that I haven't looked at this since my last comment, and I have removed my test installations since then.

**Comment by furlongm** [comment] 2018-10-07 04:28
Closing as there is no new information. Feel free to reopen if you install again.

**Closed by furlongm** 2018-10-07 04:28 UTC
